[workspace]
authors = ["ethanc8 <echaroenpitaks@gmail.com>"]
channels = ["conda-forge"]
name = "lagos-gtfs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
pandas = ">=2.3.3,<3"
openpyxl = ">=3.1.5,<4"
